import fs from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {getPublic} from './refresh.mjs';
const root=new URL('../',import.meta.url);
const read=async p=>JSON.parse(await fs.readFile(new URL(p,root),'utf8'));
const decodeHtml=(html)=>html.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');
const strip=html=>decodeHtml(html).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const hrefs=(html,base)=>[...html.matchAll(/href\s*=\s*["']([^"']+)["']/gi)].map(m=>{try{return new URL(decodeHtml(m[1]),base).href}catch{return null}}).filter(Boolean);
export const canonical=value=>{const u=new URL(value);u.hash='';for(const k of [...u.searchParams.keys()])if(k==='ref'||k.startsWith('utm_'))u.searchParams.delete(k);return u.href.replace(/[?&]$/,'')};
const titleOf=html=>strip((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||'').replace(/\s*[|｜].*$/,'').trim();
export function select(source,links){const unique=[...new Set(links.map(canonical))];if(source==='atcosme')return unique.filter(u=>/^https:\/\/www\.cosme\.net\/(?:present\/detail\/present_id\/\d+|brandcollection\/present\/detail\/present_id\/\d+|brands\/\d+\/tieup\/[^/?]+\/page\.html)\/?$/i.test(u));if(source==='Monipla')return unique.filter(u=>/^https:\/\/monipla\.jp\/[\w-]+\/[\w-]+\/?$/i.test(u)&&!/(?:\/mp\/|\/list_|\/faq_|\/kiyaku_|\/inquiry_|\/member_|\/lp_top\/)/i.test(u));if(source==='RoomClip')return unique.filter(u=>/^https:\/\/roomclip\.jp\/(?:form\/\d+|mag\/archives\/\d+)\/?$/i.test(u));return []}
async function main(){const policy=await read('data/source-policy.json');const reviewed=await read('data/reviewed-campaigns.json');const known=new Set(reviewed.map(c=>canonical(c.url)));const found=[];for(const d of policy.discovery.filter(x=>x.enabled)){try{const page=await getPublic(d.url,policy.allowedDomains);const candidates=select(d.source,hrefs(page.html,page.url)).filter(u=>!known.has(u)).slice(0,60);for(const url of candidates){let title='';let status='candidate';try{const r=await getPublic(url,policy.allowedDomains);title=titleOf(r.html);if(!title)status='needs-review'}catch{status='unreachable'}found.push({source:d.source,url,title,status})}}catch(e){found.push({source:d.source,url:d.url,title:'',status:'source-error',reason:e.message})}}
const dedup=[...new Map(found.map(x=>[x.url,x])).values()].sort((a,b)=>a.source.localeCompare(b.source,'ja')||a.url.localeCompare(b.url));const out={schemaVersion:1,generatedAt:new Date().toISOString(),count:dedup.length,candidates:dedup};await fs.writeFile(new URL('data/discovered-campaigns.json',root),JSON.stringify(out,null,2)+'\n','utf8');console.log(JSON.stringify({discovered:dedup.length,sources:Object.fromEntries([...new Set(dedup.map(x=>x.source))].map(s=>[s,dedup.filter(x=>x.source===s).length]))}))}
if(process.argv[1]===fileURLToPath(import.meta.url))await main();
