import fs from 'node:fs/promises';
import {lookup} from 'node:dns/promises';
import {isIP} from 'node:net';
import {fileURLToPath} from 'node:url';
import {rank,safeUrl,expired} from '../public/core.mjs';
const root=new URL('../',import.meta.url);
const read=async p=>JSON.parse(await fs.readFile(new URL(p,root),'utf8'));
const fields=['id','source','genre','name','prize','winners','winnersText','deadline','condition','entryType','url','applyUrl','requiresPurchase','requiresReview','requiresApp','requiresLogin','isMonitor','cost','updatedAt','productType','awardType','priorityOverride','hidden'];
export function isPublicIP(ip){if(ip.includes(':'))return /^[23]/.test(ip)&&!ip.startsWith('2001:db8:');let [a,b]=ip.split('.').map(Number);return ![0,10,127].includes(a)&&a<224&&!(a===169&&b===254)&&!(a===172&&b>=16&&b<=31)&&!(a===192&&(b===168||b===0))&&!(a===100&&b>=64&&b<=127)&&!(a===198&&(b===18||b===19))}
export async function getPublic(url,domains){for(let i=0;i<5;i++){if(!safeUrl(url,domains))throw new Error('unapproved-url');const u=new URL(url);if(isIP(u.hostname))throw new Error('ip-url');const ips=await lookup(u.hostname,{all:true});if(!ips.length||ips.some(x=>!isPublicIP(x.address)))throw new Error('nonpublic-address');const r=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(10000),headers:{'User-Agent':'KenshoPublicLinkCheck/1.0','Accept':'text/html'}});if([301,302,303,307,308].includes(r.status)){const loc=r.headers.get('location');if(!loc)throw new Error('missing-location');url=new URL(loc,url).href;await r.body?.cancel();continue}if(!r.ok)throw new Error('http-'+r.status);if(!r.headers.get('content-type')?.includes('text/html'))throw new Error('non-html');const reader=r.body.getReader();let parts=[],size=0;while(true){let {done,value}=await reader.read();if(done)break;size+=value.length;if(size>2000000){await reader.cancel();throw new Error('oversize')}parts.push(value)}return {url,html:new TextDecoder(/charset=([\w-]+)/i.exec(r.headers.get('content-type'))?.[1]||'utf-8').decode(Buffer.concat(parts))}}throw new Error('redirect-limit')}
export function clean(c,domains){const o=Object.fromEntries(fields.filter(k=>c[k]!==undefined).map(k=>[k,c[k]]));if(!/^campaign-[\w-]+$/.test(o.id)||!o.name||!o.source||!safeUrl(o.url,domains))throw new Error('invalid-campaign');for(let k of ['name','prize','condition','source','winnersText'])if(typeof o[k]!=='string'||o[k].length>600||/[\w.+-]+@[\w.-]+\.[a-z]{2,}|(?:cookie|bearer|password|session[_ -]?id)\s*[:=]/i.test(o[k]))throw new Error('invalid-text');if(o.deadline&&!/^\d{4}-\d{2}-\d{2}(?:T\d{2}:\d{2}:\d{2}(?:Z|[+-]\d{2}:\d{2}))?$/.test(o.deadline))throw new Error('invalid-deadline');if(o.deadline&&!Number.isFinite(Date.parse(o.deadline)))throw new Error('invalid-deadline');if(!['SS','S','A','B','C',undefined].includes(o.priorityOverride))throw new Error('priority');if(o.applyUrl&&!safeUrl(o.applyUrl,domains))o.applyUrl=null;return {...o,...rank(o)}}
export function endedPage(html){const title=(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||'';return /募集終了|応募終了|受付終了|ページが見つかりません|404 not found/i.test(title)||/(?:本キャンペーン|本イベント|このキャンペーン)[\s\S]{0,50}(?:は終了しました|の募集は終了)/.test(html)}
export function dedupe(rows){let seen=new Set();return rows.filter(c=>{const u=new URL(c.url);u.hash='';for(const k of [...u.searchParams.keys()])if(k.startsWith('utm_'))u.searchParams.delete(k);const key=u.href;const alternate=c.name.normalize('NFKC').replace(/\s+/g,'')+'|'+c.deadline;if(seen.has(key)||seen.has(alternate))return false;seen.add(key);seen.add(alternate);return true})}
async function replaceFile(tmp,target){try{await fs.rename(tmp,target)}catch(e){if(process.platform==='win32'&&['EPERM','EACCES'].includes(e.code)){await fs.copyFile(tmp,target);await fs.rm(tmp,{force:true})}else throw e}}
async function main(){const policy=await read('data/source-policy.json');const raw=await read('data/reviewed-campaigns.json');let prev;try{prev=await read('public/public-campaigns.json')}catch{prev={campaigns:[]}}let rows=dedupe(raw.map(c=>clean(c,policy.allowedDomains)));const now=new Date().toISOString();let log=[];let index=0;const workers=Array.from({length:4},async()=>{while(index<rows.length){const c=rows[index++];if(c.hidden){c.linkStatus='hidden';continue}if(expired(c)){c.linkStatus='ended';continue}if(policy.manualOnly.includes(new URL(c.url).hostname)){const verified=raw.find(x=>x.id===c.id);if(verified.manualVerifiedAt&&Date.now()-Date.parse(verified.manualVerifiedAt)<48*3600000){c.linkStatus='ok';c.linkCheckedAt=verified.manualVerifiedAt}else c.linkStatus='pending';log.push({id:c.id,result:c.linkStatus,reason:'manual-source'});continue}try{const r=await getPublic(c.url,policy.allowedDomains);c.linkStatus=endedPage(r.html)?'ended':'ok';c.linkCheckedAt=now;if(c.applyUrl){try{const a=await getPublic(c.applyUrl,policy.allowedDomains);if(endedPage(a.html))c.applyUrl=null}catch{c.applyUrl=null}}log.push({id:c.id,result:c.linkStatus})}catch(e){c.linkStatus='pending';c.linkCheckedAt=prev.campaigns.find(p=>p.id===c.id)?.linkCheckedAt||null;log.push({id:c.id,result:'pending',reason:e.message})}}});await Promise.all(workers);const data={schemaVersion:1,updatedAt:now,allowedDomains:policy.allowedDomains,campaigns:rows};const tmp=new URL('public/public-campaigns.json.tmp',root),target=new URL('public/public-campaigns.json',root);await fs.writeFile(tmp,JSON.stringify(data,null,2)+'\n');await replaceFile(tmp,target);await fs.writeFile(new URL('data/link-report.json',root),JSON.stringify({checkedAt:now,results:log},null,2)+'\n');console.log(JSON.stringify({total:rows.length,ok:rows.filter(c=>c.linkStatus==='ok').length,pending:rows.filter(c=>c.linkStatus==='pending').length,ended:rows.filter(c=>c.linkStatus==='ended').length}));}
if(process.argv[1]===fileURLToPath(import.meta.url))await main();
